import { Router, type IRouter } from "express";
import healthRouter from "./health";
import targetsRouter from "./targets";
import targetNestedRouter from "./target-nested-routes";
import actionsRouter from "./actions";
import interactionsRouter from "./interactions";
import importRouter from "./import";
import aiRouter from "./ai";
import reviewRouter from "./review";
import diligenceRouter from "./diligence";
import documentsRouter from "./documents";
import icSessionsRouter from "./ic-sessions";
import icProposalsRouter from "./ic-proposals";
import analyticsRouter from "./analytics";
import valuationsRouter from "./valuations";
import synergiesRouter from "./synergies";
import exportRouter from "./export";
import advisorsRouter from "./advisors";
import sponsorsRouter from "./sponsors";
import ndaRecordsRouter from "./nda-records";
import regulatoryClearancesRouter from "./regulatory-clearances";
import notificationsRouter from "./notifications";
import auditRouter from "./audit";
import adminRouter from "./admin";
import doctrineRouter from "./doctrine";
import icBriefRouter from "./ic-brief";
import { requireRole } from "../middlewares/auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/export", exportRouter);
router.use("/targets", targetsRouter);
router.use("/targets", targetNestedRouter);
router.use("/actions", actionsRouter);
router.use("/interactions", interactionsRouter);
router.use("/import", importRouter);
router.use("/ai", aiRouter);
router.use("/review", reviewRouter);
router.use("/diligence", diligenceRouter);
router.use("/documents", documentsRouter);
router.use("/ic-sessions", icSessionsRouter);
router.use(icProposalsRouter);
router.use("/analytics", analyticsRouter);
router.use("/valuations", valuationsRouter);
router.use("/synergies", synergiesRouter);
router.use("/advisors", advisorsRouter);
router.use("/sponsors", sponsorsRouter);
router.use("/nda-records", ndaRecordsRouter);
router.use("/regulatory-clearances", regulatoryClearancesRouter);
router.use("/notifications", notificationsRouter);
router.use("/audit", auditRouter);
router.use("/admin", requireRole("Admin"), adminRouter);
router.use("/doctrine", doctrineRouter);
router.use("/targets", icBriefRouter);

export default router;

